### ISSUE TITLE
Export test events to .csv

### ISSUE THREAD

**Issue by timothybest-usds** [CDCgov/prime-data-input-client#159]
TODO
[x] add a mechanism to export test events

Example https://gist.github.com/timothybest-usds/11fba7410952eafab50d35bc7bcfb4bf

Open Questions/ TODO
- [ ] Is our format of values okay
    - `Patient_DOB`
    - `Patient_gender`
    - `Patient_ethnicity`
    - `Test_result_code`
    - `Employed_in_healthcare`
    - `Resident_congregate_setting`
- [ ] What is `Specimen_source_site_code`?
- [ ] What is `Specimen_type_code`
- [ ] split ordering provider `name` into `first_name`, `last_name`
- [ ] what is `Testing_lab_ID` CLIA Number? our database unique identifier?
- [ ] we have one organization should its information be in `testing_lab` and/or `ordering_facility`.
     - `Testing_lab_name` Ordering_facility_name`
     - `_state`
     - `_street`
     - `_street2`
     - `_zip_code`
     - `_county` Note the example has a` Ordering_facility_county` but not a `testing_lab_county`
- [ ] what is `Ordered_test_code`?
- [ ] what is `Specimen_source_site_code`?
- [ ] what is `Specimen_type_code`?
- [ ] `Instrument_ID` is the device IONIC code?
- [ ] What is the difference between `Test_date` and `Date_result_released`

**Comment by aliciabeckett-gov** [comment]
Should be a full dump of MVP required fields before they are translated by the data hub.

[expected headers.xlsx](https://github.com/CDCgov/prime-data-input-client/files/5587565/expected.headers.xlsx)

**Comment by jimduff-usds** [comment]
OK, I owe you a few more answers, but here's a first pass.

Formats:
-  `Patient_DOB`.     We currently expect yyyymmdd, eg, 19850531
- `Patient_gender`.  We expect single uppercase letter , eg, F, A (ambiguous), O (other), N (not applicable), M
- `Patient_ethnicity`. We expect single uppercase letter, eg, U (unknown), N (not hisp), H (hisp)
- `Test_result_code`. We expect numeric codes as follows:
```
    - code: 260373001
      display: Detected
    - code: 260415000
      display: Not detected
    - code: 895231008
      display: Not detected in pooled specimen
    - code: 462371000124108
      display: Detected in pooled specimen
    - code: 419984006
      display: Inconclusive
```
- `Employed_in_healthcare`.  We expect Y, N, or UNK.   (Note:  It looks like AZ PHD does not current expect this field)
- `Resident_congregate_setting` We expect Y, Y, UNK.  _This seems fishy to me - need to doublecheck_.  (Note:  It looks like AZ PHD does not current expect this field)

- [ ] What is `Specimen_source_site_code`?  **Answer**:  We don't have a value set for this yet.   AZ PHD example for this is "Forearm".

- [ ] What is Specimen_type_code.  **Answer**:  as follows...
```
- name: covid-19/specimen_type
  system: SNOMED_CT
  referenceUrl: https://www.hhs.gov/sites/default/files/hhs-guidance-implementation.pdf
  values:
    - code: 258500001
      display: Nasopharyngeal swab
    - code: 871810001
      display: Mid-turbinate nasal swab
    - code: 697989009
      display: Anterior nares swab
    - code: 258411007
      display: Nasopharyngeal aspirate
    - code: 429931000124105
      display: Nasal aspirate
    - code: 258529004
      display: Throat swab
    - code: 119334006
      display: Sputum specimen
    - code: 119342007
      display: Saliva specimen
    - code: 258607008
      display: Bronchoalveolar lavage fluid sample
    - code: 119364003
      display: Serum specimen
    - code: 119361006
      display: Plasma specimen
    - code: 440500007
      display: Dried blood spot specimen
    - code: 258580003
      display: Whole blood sample
    - code: 122555007
      display: Venous blood specimen
```

- [ ]  split ordering provider name into first_name, last_name.   **Answer**:  Yes, AZ PHD is expecting these as two separate fields.

- [ ]   what is Testing_lab_ID CLIA Number? our database unique identifier?  **Answer**: Not sure. @jlusds ??   Does SimpleReport get a Clia number or, more likely, this is different for each lab using SimpleReport.

- [ ]   we have one organization should its information be in testing_lab and/or ordering_facility.  **Answer**: Not sure.  @jlusds  ??
```
Testing_lab_name Ordering_facility_name`
_state
_street
_street2
_zip_code
_county Note the example has a Ordering_facility_county but not a testing_lab_county
```
  what is Ordered_test_code?  **Answer**:
```
- name: covid-19/order
  system: LOINC
  reference: Incomplete - Supports BD Veritor, Quidell Sofia, and Abbott ID Now
  referenceUrl: https://www.cdc.gov/csels/dls/documents/livd_test_code_mapping/LIVD-SARS-CoV-2-2020-10-21.xlsx
  values:
    - code: 94563-4
      display: SARS coronavirus 2 IgG Ab [Presence] in Serum or Plasma by Immunoassay
    - code: 94500-6
      display: SARS coronavirus 2 RNA [Presence] in Respiratory specimen by NAA with probe detection
    - code: 94558-4
      display: SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay
    - code: 94534-5
      display: SARS coronavirus 2 RdRp gene [Presence] in Respiratory specimen by NAA with probe detection
    - code: 94564-2
      display: SARS-CoV-2 (COVID-19) IgM Ab [Presence] in Serum or Plasma by Immunoassay
    - code: 94531-1
      display: SARS coronavirus 2 RNA panel - Respiratory specimen by NAA with probe detection
    - code: 94559-2
      display: SARS coronavirus 2 ORF1ab region [Presence] in Respiratory specimen by NAA with probe detection
    - code: 95209-3
      display: SARS coronavirus+SARS coronavirus 2 Ag [Presence] in Respiratory specimen by Rapid immunoassay
```

- [ ]   what is Specimen_source_site_code?  **Answer**:  Answered this above.

- [ ]   what is Specimen_type_code?  **Answer**:  Answered this above.

- [ ]   Instrument_ID is the device IONIC code?  **Answer**:  _Not sure._  I need to get back to you.   It looks like we expect a numeric ID for this right now.  No enumerated set of values

- [ ]  What is the difference between Test_date and Date_result_released.   **Answer**:   AZ PHD expects two dates:  the "Collection date" and the "Result Date".    I presume test_date is the date the sample was collected.

Whew!!
